name: Moodle Plugin Release

########################################################################################################################

on:
  release:
    types: [ published ]

########################################################################################################################

jobs:
  call-moodle-release-workflow:
    uses: Opencast-Moodle/moodle-workflows-opencast/.github/workflows/moodle-release.yml@main
    with:
      plugin-name: 'block_opencast'
    secrets: inherit
