name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  call-moodle-ci-workflow:
    uses: Opencast-Moodle/moodle-workflows-opencast/.github/workflows/moodle-ci.yml@3bab5ce2b4a324cdff6b1f39a168ccf92f7bcf2f
    with:
      requires-tool-plugin: true
      requires-mod-plugin: true
